In [108]:
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [81]:
list=["Country","Year","Status","Adult_Mortality","infant_deaths","Alcohol","percentage_expenditure","HepatitisB","Measles","BMI","under_five_deaths","Polio","Total_expenditure","Diphtheria"," HIV/AIDS","GDP","Population","thinness1_19years","thinness5_9years","Income_composition_of_resources","Schooling","Life_expectancy"]

In [82]:
data=pd.read_csv("C:/Users/admin/Downloads/Life Expectancy Data.csv",header=0,names=list)

In [83]:
data.isnull().sum()

Country                              0
Year                                 0
Status                               0
Adult_Mortality                     10
infant_deaths                        0
Alcohol                            194
percentage_expenditure               0
HepatitisB                         553
Measles                              0
BMI                                 34
under_five_deaths                    0
Polio                               19
Total_expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
thinness1_19years                   34
thinness5_9years                    34
Income_composition_of_resources    167
Schooling                          163
Life_expectancy                     10
dtype: int64

In [106]:
data.head()

,Country,Year,Status,Adult_Mortality,infant_deaths,Alcohol,percentage_expenditure,HepatitisB,Measles,BMI,...,Total_expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness1_19years,thinness5_9years,Income_composition_of_resources,Schooling,Life_expectancy
0,0,2015,1,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,0,2014,1,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,0,2013,1,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,0,2012,1,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,0,2011,1,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [85]:
data.shape

(2938, 22)

In [86]:
data.Adult_Mortality .interpolate(method='pad',inplace=True)

In [87]:
data.Alcohol.interpolate(method='pad',inplace=True)

In [88]:
data.HepatitisB.interpolate(method='pad',inplace=True)

In [89]:
data.BMI.interpolate(method='pad',inplace=True)

In [90]:
data.Polio.interpolate(method='pad',inplace=True)

In [91]:
data.Total_expenditure.interpolate(method='pad',inplace=True)

In [92]:
data.Diphtheria.interpolate(method='pad',inplace=True)

In [93]:
data.GDP.interpolate(method='pad',inplace=True)

In [94]:
data.Population.interpolate(method='pad',inplace=True)

In [95]:
data.thinness1_19years.interpolate(method='pad',inplace=True)

In [96]:
data.thinness5_9years.interpolate(method='pad',inplace=True)

In [97]:
data.Income_composition_of_resources .interpolate(method='pad',inplace=True)

In [98]:
data.Schooling.interpolate(method='pad',inplace=True)

In [99]:
data.Life_expectancy.interpolate(method='pad',inplace=True)

In [100]:
data.isnull().sum()

Country                            0
Year                               0
Status                             0
Adult_Mortality                    0
infant_deaths                      0
Alcohol                            0
percentage_expenditure             0
HepatitisB                         0
Measles                            0
BMI                                0
under_five_deaths                  0
Polio                              0
Total_expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
thinness1_19years                  0
thinness5_9years                   0
Income_composition_of_resources    0
Schooling                          0
Life_expectancy                    0
dtype: int64

In [102]:
le = preprocessing.LabelEncoder()

In [103]:
data.Country=le.fit_transform(data.Country)

In [105]:
data.Status=le.fit_transform(data.Status)

In [109]:
scaler = StandardScaler()

In [111]:
scaleddata=scaler.fit_transform(data)

In [113]:
scaleddata=pd.DataFrame(scaleddata)

In [114]:
scaleddata.columns=data.columns

In [116]:
scaleddata.head()

,Country,Year,Status,Adult_Mortality,infant_deaths,Alcohol,percentage_expenditure,HepatitisB,Measles,BMI,...,Total_expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness1_19years,thinness5_9years,Income_composition_of_resources,Schooling,Life_expectancy
0,-1.691042,1.621762,0.459399,0.789176,0.268824,-1.136785,-0.335570,-0.370362,-0.110384,-0.937958,...,0.907653,-0.714057,-0.323445,-0.502060,0.365388,2.696551,2.633648,-0.722755,-0.549662,-0.440024
1,-1.691042,1.404986,0.459399,0.853479,0.285786,-1.136785,-0.334441,-0.474359,-0.168124,-0.962745,...,0.915704,-0.839512,-0.323445,-0.499988,-0.228123,2.762622,2.676480,-0.736981,-0.579606,-0.974894
2,-1.691042,1.188210,0.459399,0.829365,0.302749,-1.136785,-0.334594,-0.405028,-0.173531,-0.987532,...,0.895577,-0.755876,-0.323445,-0.498600,0.329773,2.806668,2.719313,-0.765432,-0.609549,-0.974894
3,-1.691042,0.971434,0.459399,0.861516,0.328193,-1.136785,-0.332096,-0.301031,0.032045,-1.012320,...,1.052569,-0.630421,-0.323445,-0.495816,-0.168266,2.850715,2.783562,-0.798626,-0.639492,-1.016844
4,-1.691042,0.754658,0.459399,0.885630,0.345155,-1.136785,-0.367862,-0.266365,0.051757,-1.032149,...,0.790915,-0.588602,-0.323445,-0.539996,-0.181028,2.916785,2.826394,-0.841303,-0.729323,-1.048307

In [117]:
Y=scaleddata.Life_expectancy

In [120]:
X=scaleddata.drop('Life_expectancy',axis=1)

In [121]:
X.head()

,Country,Year,Status,Adult_Mortality,infant_deaths,Alcohol,percentage_expenditure,HepatitisB,Measles,BMI,...,Polio,Total_expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness1_19years,thinness5_9years,Income_composition_of_resources,Schooling
0,-1.691042,1.621762,0.459399,0.789176,0.268824,-1.136785,-0.335570,-0.370362,-0.110384,-0.937958,...,-3.228909,0.907653,-0.714057,-0.323445,-0.502060,0.365388,2.696551,2.633648,-0.722755,-0.549662
1,-1.691042,1.404986,0.459399,0.853479,0.285786,-1.136785,-0.334441,-0.474359,-0.168124,-0.962745,...,-1.028564,0.915704,-0.839512,-0.323445,-0.499988,-0.228123,2.762622,2.676480,-0.736981,-0.579606
2,-1.691042,1.188210,0.459399,0.829365,0.302749,-1.136785,-0.334594,-0.405028,-0.173531,-0.987532,...,-0.859306,0.895577,-0.755876,-0.323445,-0.498600,0.329773,2.806668,2.719313,-0.765432,-0.609549
3,-1.691042,0.971434,0.459399,0.861516,0.328193,-1.136785,-0.332096,-0.301031,0.032045,-1.012320,...,-0.647735,1.052569,-0.630421,-0.323445,-0.495816,-0.168266,2.850715,2.783562,-0.798626,-0.639492
4,-1.691042,0.754658,0.459399,0.885630,0.345155,-1.136785,-0.367862,-0.266365,0.051757,-1.032149,...,-0.605420,0.790915,-0.588602,-0.323445,-0.539996,-0.181028,2.916785,2.826394,-0.841303,-0.729323